block
    block
    columns 1
    Smartphone
    a space e
    e["sync layer"]
    a["Flutter\napp"] --> e
    e --> a
    e space b
    b["Data\nLayer"]
    e --> b
    b --> e
    end
    space 
    block
    columns 1
    wearOS
    d space f
    f["sync layer"]
    d["Flutter\napp"] --> f
    f --> d
    f space c
    c["Data\nLayer"]
    c --> f
    f --> c
    end
    b -- "bluetooth" --> c
    c -- "bluetooth" --> b

    style Smartphone stroke:transparent, fill:transparent
    style wearOS stroke:transparent, fill:transparent
