sequenceDiagram
    autonumber
    participant home as Homepage
    participant osm as OpenStreetMap
    participant tds as Trail Details Page
    participant oPass as Overpass
    participant aap as Add Activity Page
    participant db as Database Service
    participant f@{ "type": "database", "alias": "Internal DB" } as Firebase

    home ->>+ osm: searchLocation(name)
    alt location not found
        osm --> home: Error: Location not found
    else
        osm -->- home: location
        home ->>+ oPass: searchTrails(location)
        alt trails not found
            oPass --> home: Error: no trail found in this location
        else
            oPass -->- home: list<trails>
            home ->> home: select trail
            home ->> tds: tap on trail
            tds ->>+ oPass: fetchTrailDetail(trail)
            oPass -->- tds: details
            alt go back operation
                tds ->> home: return()
            else
                tds ->> aap: plan button
                alt go back operation
                    aap ->> tds: return()
                else
                    aap ->> aap: compile plan form
                    aap ->> aap: save button
                    aap ->>+ db: addActivity(activity)
                    db ->>+ f: API call()
                    f -->- db: response
                    db -->- aap: response 
                end
            end
        end
    end