sequenceDiagram
    autonumber
    participant phone
    participant ps as phone_sync
    participant pdl as phone_data_layer
    participant wdl as watch_data_layer
    participant ws as wear_sync
    participant watch

    phone ->> phone: compute stats
    phone ->> ps: sendStats(stats)
    ps ->> pdl: invokeMethod("sendStatsToWatch", statsJson)
    pdl ->> wdl: sendMessageToWatch(method + stats)
    alt "is not connected"
        wdl ->> wdl: sendToCache
    else
        wdl ->> ws: invokeMethod("handleMethodCallFromPhone", method, statsJson)
        ws ->> watch: onStatsUpdate(stats)
        watch ->> watch: refresh UI
    end
