// Mocks generated by Mockito 5.4.6 from annotations
// in application/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:application/core/cubit/profile_cubit.dart' as _i8;
import 'package:application/core/cubit/settings_cubit.dart' as _i4;
import 'package:application/core/models/profile.dart' as _i3;
import 'package:application/core/models/settings.dart' as _i2;
import 'package:application/core/repository/settings_repository.dart' as _i13;
import 'package:application/services/auth_service.dart' as _i9;
import 'package:application/services/database_service.dart' as _i11;
import 'package:cloud_firestore/cloud_firestore.dart' as _i12;
import 'package:firebase_auth/firebase_auth.dart' as _i10;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettings_0 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsCubit extends _i1.Mock implements _i4.SettingsCubit {
  MockSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Settings get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSettings_0(this, Invocation.getter(#state)),
          )
          as _i2.Settings);

  @override
  _i5.Stream<_i2.Settings> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.Settings>.empty(),
          )
          as _i5.Stream<_i2.Settings>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  void updateNotifications(bool? value) => super.noSuchMethod(
    Invocation.method(#updateNotifications, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFerrata(bool? value) => super.noSuchMethod(
    Invocation.method(#updateFerrata, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDifficulty(double? value) => super.noSuchMethod(
    Invocation.method(#updateDifficulty, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Settings? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i2.Settings?);

  @override
  Map<String, dynamic> toJson(_i2.Settings? state) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [state]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i2.Settings? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.Settings>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i7.Storage? storage,
    _i7.OnHydrationError? onError = _i7.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfileCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileCubit extends _i1.Mock implements _i8.ProfileCubit {
  MockProfileCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Profile get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProfile_1(this, Invocation.getter(#state)),
          )
          as _i3.Profile);

  @override
  _i5.Stream<_i3.Profile> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.Profile>.empty(),
          )
          as _i5.Stream<_i3.Profile>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  void updateNickname(String? value) => super.noSuchMethod(
    Invocation.method(#updateNickname, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateXp(double? value) => super.noSuchMethod(
    Invocation.method(#updateXp, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Profile? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i3.Profile?);

  @override
  Map<String, dynamic> toJson(_i3.Profile? state) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [state]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.Profile? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.Profile>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i7.Storage? storage,
    _i7.OnHydrationError? onError = _i7.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.User?> registerUser(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [email, password]),
            returnValue: _i5.Future<_i10.User?>.value(),
          )
          as _i5.Future<_i10.User?>);

  @override
  _i5.Future<_i10.User?> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i10.User?>.value(),
          )
          as _i5.Future<_i10.User?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i11.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> createUser(String? email, String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [email, nickname]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> fetchDocument(
    _i12.DocumentReference<Map<String, dynamic>>? doc,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDocument, [doc]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> saveDocument(
    _i12.DocumentReference<Map<String, dynamic>>? doc,
    Map<String, dynamic>? data, {
    bool? merge = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveDocument, [doc, data], {#merge: merge}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<Map<String, dynamic>?> streamDocument(
    _i12.DocumentReference<Map<String, dynamic>>? doc,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamDocument, [doc]),
            returnValue: _i5.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> fetchSettings() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSettings, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> saveSettings(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<Map<String, dynamic>?> streamSettings() =>
      (super.noSuchMethod(
            Invocation.method(#streamSettings, []),
            returnValue: _i5.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> fetchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> saveProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<Map<String, dynamic>?> streamProfile() =>
      (super.noSuchMethod(
            Invocation.method(#streamProfile, []),
            returnValue: _i5.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>?>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i13.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Settings?> fetchRemote() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRemote, []),
            returnValue: _i5.Future<_i2.Settings?>.value(),
          )
          as _i5.Future<_i2.Settings?>);

  @override
  _i5.Future<void> saveRemote(_i2.Settings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveRemote, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i2.Settings?> streamRemote() =>
      (super.noSuchMethod(
            Invocation.method(#streamRemote, []),
            returnValue: _i5.Stream<_i2.Settings?>.empty(),
          )
          as _i5.Stream<_i2.Settings?>);
}

/// A class which mocks [Settings].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettings extends _i1.Mock implements _i2.Settings {
  MockSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get notifications =>
      (super.noSuchMethod(Invocation.getter(#notifications), returnValue: false)
          as bool);

  @override
  bool get ferrata =>
      (super.noSuchMethod(Invocation.getter(#ferrata), returnValue: false)
          as bool);

  @override
  double get difficulty =>
      (super.noSuchMethod(Invocation.getter(#difficulty), returnValue: 0.0)
          as double);

  @override
  _i2.Settings copyWith({
    bool? notifications,
    bool? ferrata,
    double? difficulty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #notifications: notifications,
              #ferrata: ferrata,
              #difficulty: difficulty,
            }),
            returnValue: _FakeSettings_0(
              this,
              Invocation.method(#copyWith, [], {
                #notifications: notifications,
                #ferrata: ferrata,
                #difficulty: difficulty,
              }),
            ),
          )
          as _i2.Settings);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
